### ISSUE TITLE
Hostlist expansion output is incorrect on range [1-1]

### ISSUE THREAD

**Issue by emdonat** [ovis-hpc/ldms#1577]
When using a hostlist like admin[1-1] in a yaml configuration file, certain configurations show up multiply.  e.g.

for:
```
- names: "admin[1-1]"
  hosts: "admin[1-1]"
  endpoints:
  - names: admin[1-1]-ib1"
    ports: 411
    xprt: sock
    auth:
      name: ovis
      plugin: ovis
```
```
auth_add name=ovis plugin=ovis conf=/tmp/inst/auth.conf
listen xprt=sock port=413 auth=ovis conf=/tmp/inst/auth.conf host=0.0.0.0

```
both show up twice for daemons using [1-1]
