### ISSUE TITLE
producers line in yaml config is not parsing correctly.

### ISSUE THREAD

**Issue by emdonat** [ovis-hpc/ldms#1579]
When adding a producers line in a yaml config for an updater under aggregators, the output configuration ignores this and instead shows a regex of .*.

```
  - daemons: "system[1-2]"
    endpoints: "system[1-2]-ib0"
    reconnect: 20s
    type: active
    updaters:
      - mode: pull
        interval: "1.0s"
        offset: "10ms"
        producers: "someregexhere"
        sets:
          - regex: ".*"
            field: inst
```
outputs 
```
updtr_prdcr_add name=updtr_0 regex=.*
```
